/* Allegro datafile object indexes, produced by grabber v4.2.2, MinGW32 */
/* Datafile: c:\c\Oddity0.04\dat\gfx.dat */
/* Date: Fri Sep 11 16:42:53 2009 */
/* Do not hand edit! */

#define AANULL                           0        /* BMP  */
#define BEE00                            1        /* BMP  */
#define BEE01                            2        /* BMP  */
#define BONUS00                          3        /* BMP  */
#define BONUS02                          4        /* BMP  */
#define BONUS03                          5        /* BMP  */
#define BONUS_BOUNCE                     6        /* BMP  */
#define BONUS_CASH                       7        /* BMP  */
#define BONUS_FIRE                       8        /* BMP  */
#define BONUS_H00                        9        /* BMP  */
#define BONUS_H01                        10       /* BMP  */
#define BONUS_LAZER                      11       /* BMP  */
#define BONUS_LIFE                       12       /* BMP  */
#define BONUS_MISSILE                    13       /* BMP  */
#define BONUS_OPTION                     14       /* BMP  */
#define BONUS_SHIELD                     15       /* BMP  */
#define BONUS_SPEED                      16       /* BMP  */
#define BOULDER00                        17       /* BMP  */
#define BOULDER01                        18       /* BMP  */
#define BOULDER02                        19       /* BMP  */
#define BUBBLE00                         20       /* BMP  */
#define BUBBLE01                         21       /* BMP  */
#define BUBBLE02                         22       /* BMP  */
#define BUBBLE03                         23       /* BMP  */
#define BULLET00                         24       /* BMP  */
#define BULLET01                         25       /* BMP  */
#define BULLET02                         26       /* BMP  */
#define BULLET03                         27       /* BMP  */
#define BULLET04                         28       /* BMP  */
#define BULLET05                         29       /* BMP  */
#define BULLET06                         30       /* BMP  */
#define BULLET07                         31       /* BMP  */
#define BULLET08                         32       /* BMP  */
#define BULLET09                         33       /* BMP  */
#define BULLET10                         34       /* BMP  */
#define BULLET11                         35       /* BMP  */
#define BULLET12                         36       /* BMP  */
#define BULLET13                         37       /* BMP  */
#define BULLET14                         38       /* BMP  */
#define BURST00                          39       /* BMP  */
#define BURST01                          40       /* BMP  */
#define BURST02                          41       /* BMP  */
#define BURST03                          42       /* BMP  */
#define CANON00                          43       /* BMP  */
#define CANON01                          44       /* BMP  */
#define CASH00                           45       /* BMP  */
#define COCKPITBEE00                     46       /* BMP  */
#define COCKPITBEE01                     47       /* BMP  */
#define COCKPITBEE02                     48       /* BMP  */
#define CRAB00                           49       /* BMP  */
#define CRAB01                           50       /* BMP  */
#define CRAB02                           51       /* BMP  */
#define CRAB03                           52       /* BMP  */
#define CREVETTE00                       53       /* BMP  */
#define CREVETTE01                       54       /* BMP  */
#define CREVETTE02                       55       /* BMP  */
#define CREVETTE03                       56       /* BMP  */
#define CREVETTE04                       57       /* BMP  */
#define CREVETTE05                       58       /* BMP  */
#define CROSS                            59       /* BMP  */
#define CURSOR                           60       /* BMP  */
#define DOUBLESHOT00                     61       /* BMP  */
#define DOUBLESHOT01                     62       /* BMP  */
#define DOUBLESHOT02                     63       /* BMP  */
#define DOUBLESHOT03                     64       /* BMP  */
#define DOUBLESHOT04                     65       /* BMP  */
#define DOUBLESHOT05                     66       /* BMP  */
#define EXPLODE00                        67       /* BMP  */
#define EXPLODE01                        68       /* BMP  */
#define EXPLODE02                        69       /* BMP  */
#define EXPLODE03                        70       /* BMP  */
#define EXPLODE04                        71       /* BMP  */
#define FISHSHIP00                       72       /* BMP  */
#define FISHSHIP01                       73       /* BMP  */
#define FISHSHIP02                       74       /* BMP  */
#define FRIENDLY00                       75       /* BMP  */
#define FRIENDLY01                       76       /* BMP  */
#define FRIENDLY02                       77       /* BMP  */
#define FRIENDLY03                       78       /* BMP  */
#define GENERATOR                        79       /* BMP  */
#define HOMING00                         80       /* BMP  */
#define HOMING01                         81       /* BMP  */
#define HOMING02                         82       /* BMP  */
#define HOMING03                         83       /* BMP  */
#define HOMING04                         84       /* BMP  */
#define HOMING05                         85       /* BMP  */
#define HOMING06                         86       /* BMP  */
#define HOMING07                         87       /* BMP  */
#define ICO_BGB_MINUS                    88       /* BMP  */
#define ICO_BGB_PLUS                     89       /* BMP  */
#define ICO_BGG_MINUS                    90       /* BMP  */
#define ICO_BGG_PLUS                     91       /* BMP  */
#define ICO_BGR_MINUS                    92       /* BMP  */
#define ICO_BGR_PLUS                     93       /* BMP  */
#define ICO_CASH                         94       /* BMP  */
#define ICO_DESTROY                      95       /* BMP  */
#define ICO_EMPTY                        96       /* BMP  */
#define ICO_EXIT                         97       /* BMP  */
#define ICO_FADE                         98       /* BMP  */
#define ICO_GAMEOVER                     99       /* BMP  */
#define ICO_MSG1                         100      /* BMP  */
#define ICO_MSG2                         101      /* BMP  */
#define ICO_MSG3                         102      /* BMP  */
#define ICO_MSG4                         103      /* BMP  */
#define ICO_NEXT                         104      /* BMP  */
#define ICO_SPEEDDOWN                    105      /* BMP  */
#define ICO_SPEEDUP                      106      /* BMP  */
#define INVADER00                        107      /* BMP  */
#define INVADER01                        108      /* BMP  */
#define INVADER02                        109      /* BMP  */
#define INVADER03                        110      /* BMP  */
#define JELLY00                          111      /* BMP  */
#define JELLY01                          112      /* BMP  */
#define JELLY02                          113      /* BMP  */
#define JELLY03                          114      /* BMP  */
#define LARVE00                          115      /* BMP  */
#define LARVE01                          116      /* BMP  */
#define LARVE02                          117      /* BMP  */
#define LARVE03                          118      /* BMP  */
#define LARVE99                          119      /* BMP  */
#define LIFE                             120      /* BMP  */
#define MACHOIRE00                       121      /* BMP  */
#define MACHOIRE01                       122      /* BMP  */
#define MACHOIRE02                       123      /* BMP  */
#define MACHOIRE03                       124      /* BMP  */
#define MEDUSE00                         125      /* BMP  */
#define MEDUSE01                         126      /* BMP  */
#define MEDUSE02                         127      /* BMP  */
#define MEDUSE03                         128      /* BMP  */
#define MEDUSE04                         129      /* BMP  */
#define MEDUSE05                         130      /* BMP  */
#define MEDUSE99                         131      /* BMP  */
#define MINE                             132      /* BMP  */
#define MOUCHE00                         133      /* BMP  */
#define MOUCHE01                         134      /* BMP  */
#define MOUCHE02                         135      /* BMP  */
#define MOUCHE03                         136      /* BMP  */
#define MOUCHE99                         137      /* BMP  */
#define MOUSE_CURSOR                     138      /* BMP  */
#define NEST00                           139      /* BMP  */
#define NEST01                           140      /* BMP  */
#define OPTION00                         141      /* BMP  */
#define OPTION01                         142      /* BMP  */
#define OPTION02                         143      /* BMP  */
#define OPTION03                         144      /* BMP  */
#define PARTICULE00                      145      /* BMP  */
#define PARTICULE01                      146      /* BMP  */
#define PARTICULE02                      147      /* BMP  */
#define RIPPLE00                         148      /* BMP  */
#define RIPPLE01                         149      /* BMP  */
#define RIPPLE02                         150      /* BMP  */
#define RIPPLE03                         151      /* BMP  */
#define RIPPLE04                         152      /* BMP  */
#define RIPPLE05                         153      /* BMP  */
#define RIPPLE06                         154      /* BMP  */
#define RIPPLE07                         155      /* BMP  */
#define RIPPLE08                         156      /* BMP  */
#define RIPPLE09                         157      /* BMP  */
#define RIPPLE10                         158      /* BMP  */
#define RIPPLE11                         159      /* BMP  */
#define RIPPLE12                         160      /* BMP  */
#define ROCKET00                         161      /* BMP  */
#define ROND                             162      /* BMP  */
#define ROND00                           163      /* BMP  */
#define ROND01                           164      /* BMP  */
#define ROTO00                           165      /* BMP  */
#define ROTO01                           166      /* BMP  */
#define ROTO02                           167      /* BMP  */
#define ROTO03                           168      /* BMP  */
#define ROTO04                           169      /* BMP  */
#define ROTO05                           170      /* BMP  */
#define SHIELD00                         171      /* BMP  */
#define SHIELD01                         172      /* BMP  */
#define SHIP00                           173      /* BMP  */
#define SHIP01                           174      /* BMP  */
#define SHIP02                           175      /* BMP  */
#define SHIP03                           176      /* BMP  */
#define SHIP04                           177      /* BMP  */
#define SHIP05                           178      /* BMP  */
#define SHIP06                           179      /* BMP  */
#define SPEED00                          180      /* BMP  */
#define SPEED01                          181      /* BMP  */
#define SPEED02                          182      /* BMP  */
#define SPEED03                          183      /* BMP  */
#define SPEED04                          184      /* BMP  */
#define SPEED05                          185      /* BMP  */
#define SPEED06                          186      /* BMP  */
#define SPEED07                          187      /* BMP  */
#define SPIKE00                          188      /* BMP  */
#define SPIKE01                          189      /* BMP  */
#define SPIKE02                          190      /* BMP  */
#define SPIKE03                          191      /* BMP  */
#define SPRITE03                         192      /* BMP  */
#define STAR00                           193      /* BMP  */
#define STAR01                           194      /* BMP  */
#define STAR02                           195      /* BMP  */
#define STAR03                           196      /* BMP  */
#define STAR04                           197      /* BMP  */
#define STAR05                           198      /* BMP  */
#define STAR06                           199      /* BMP  */
#define STAR07                           200      /* BMP  */
#define STAR08                           201      /* BMP  */
#define TIE00                            202      /* BMP  */
#define TIE01                            203      /* BMP  */
#define TIE02                            204      /* BMP  */
#define TIE03                            205      /* BMP  */
#define TIE04                            206      /* BMP  */
#define TIE05                            207      /* BMP  */
#define TIE06                            208      /* BMP  */
#define TIE07                            209      /* BMP  */

