/* Allegro datafile object indexes, produced by grabber v4.2.2, MinGW32 */
/* Datafile: c:\c\Oddity0.04\tiles.dat */
/* Date: Thu Apr 16 17:48:43 2009 */
/* Do not hand edit! */

#define TILE000                          0        /* BMP  */
#define TILE001                          1        /* BMP  */
#define TILE002                          2        /* BMP  */
#define TILE003                          3        /* BMP  */
#define TILE004                          4        /* BMP  */
#define TILE005                          5        /* BMP  */
#define TILE006                          6        /* BMP  */
#define TILE007                          7        /* BMP  */
#define TILE008                          8        /* BMP  */
#define TILE009                          9        /* BMP  */
#define TILE010                          10       /* BMP  */
#define TILE011                          11       /* BMP  */
#define TILE012                          12       /* BMP  */
#define TILE013                          13       /* BMP  */
#define TILE014                          14       /* BMP  */
#define TILE015                          15       /* BMP  */
#define TILE016                          16       /* BMP  */
#define TILE017                          17       /* BMP  */
#define TILE018                          18       /* BMP  */
#define TILE019                          19       /* BMP  */
#define TILE020                          20       /* BMP  */
#define TILE021                          21       /* BMP  */
#define TILE022                          22       /* BMP  */
#define TILE023                          23       /* BMP  */
#define TILE024                          24       /* BMP  */
#define TILE025                          25       /* BMP  */
#define TILE026                          26       /* BMP  */
#define TILE027                          27       /* BMP  */
#define TILE028                          28       /* BMP  */
#define TILE029                          29       /* BMP  */
#define TILE030                          30       /* BMP  */
#define TILE031                          31       /* BMP  */
#define TILE032                          32       /* BMP  */
#define TILE033                          33       /* BMP  */
#define TILE034                          34       /* BMP  */
#define TILE035                          35       /* BMP  */
#define TILE036                          36       /* BMP  */
#define TILE037                          37       /* BMP  */
#define TILE038                          38       /* BMP  */
#define TILE039                          39       /* BMP  */
#define TILE040                          40       /* BMP  */
#define TILE041                          41       /* BMP  */
#define TILE042                          42       /* BMP  */
#define TILE043                          43       /* BMP  */
#define TILE044                          44       /* BMP  */
#define TILE045                          45       /* BMP  */
#define TILE046                          46       /* BMP  */
#define TILE047                          47       /* BMP  */
#define TILE048                          48       /* BMP  */
#define TILE049                          49       /* BMP  */
#define TILE050                          50       /* BMP  */
#define TILE051                          51       /* BMP  */
#define TILE052                          52       /* BMP  */
#define TILE053                          53       /* BMP  */
#define TILE054                          54       /* BMP  */
#define TILE055                          55       /* BMP  */
#define TILE056                          56       /* BMP  */
#define TILE057                          57       /* BMP  */
#define TILE058                          58       /* BMP  */
#define TILE059                          59       /* BMP  */
#define TILE060                          60       /* BMP  */
#define TILE061                          61       /* BMP  */
#define TILE062                          62       /* BMP  */
#define TILE063                          63       /* BMP  */
#define TILE064                          64       /* BMP  */
#define TILE065                          65       /* BMP  */
#define TILE066                          66       /* BMP  */
#define TILE067                          67       /* BMP  */
#define TILE068                          68       /* BMP  */
#define TILE069                          69       /* BMP  */
#define TILE070                          70       /* BMP  */
#define TILE071                          71       /* BMP  */
#define TILE072                          72       /* BMP  */
#define TILE073                          73       /* BMP  */
#define TILE074                          74       /* BMP  */
#define TILE075                          75       /* BMP  */
#define TILE076                          76       /* BMP  */
#define TILE077                          77       /* BMP  */
#define TILE078                          78       /* BMP  */
#define TILE079                          79       /* BMP  */
#define TILE080                          80       /* BMP  */
#define TILE081                          81       /* BMP  */
#define TILE082                          82       /* BMP  */
#define TILE083                          83       /* BMP  */
#define TILE084                          84       /* BMP  */
#define TILE085                          85       /* BMP  */
#define TILE086                          86       /* BMP  */
#define TILE087                          87       /* BMP  */
#define TILE088                          88       /* BMP  */
#define TILE089                          89       /* BMP  */
#define TILE090                          90       /* BMP  */
#define TILE091                          91       /* BMP  */
#define TILE092                          92       /* BMP  */
#define TILE093                          93       /* BMP  */
#define TILE094                          94       /* BMP  */
#define TILE095                          95       /* BMP  */
#define TILE096                          96       /* BMP  */
#define TILE097                          97       /* BMP  */
#define TILE098                          98       /* BMP  */
#define TILE099                          99       /* BMP  */
#define TILE100                          100      /* BMP  */
#define TILE101                          101      /* BMP  */
#define TILE102                          102      /* BMP  */
#define TILE103                          103      /* BMP  */
#define TILE104                          104      /* BMP  */
#define TILE104                          105      /* BMP  */
#define TILE105                          106      /* BMP  */
#define TILE106                          107      /* BMP  */
#define TILE107                          108      /* BMP  */
#define TILE108                          109      /* BMP  */
#define TILE109                          110      /* BMP  */
#define TILE110                          111      /* BMP  */
#define TILE111                          112      /* BMP  */
#define TILE112                          113      /* BMP  */
#define TILE113                          114      /* BMP  */
#define TILE114                          115      /* BMP  */
#define TILE115                          116      /* BMP  */
#define TILE116                          117      /* BMP  */
#define TILE117                          118      /* BMP  */
#define TILE118                          119      /* BMP  */
#define TILE119                          120      /* BMP  */
#define TILE120                          121      /* BMP  */
#define TILE121                          122      /* BMP  */
#define TILE122                          123      /* BMP  */
#define TILE123                          124      /* BMP  */
#define TILE124                          125      /* BMP  */
#define TILE125                          126      /* BMP  */
#define TILE126                          127      /* BMP  */
#define TILE127                          128      /* BMP  */
#define TILE128                          129      /* BMP  */
#define TILE129                          130      /* BMP  */
#define TILE130                          131      /* BMP  */
#define TILE131                          132      /* BMP  */
#define TILE132                          133      /* BMP  */
#define TILE133                          134      /* BMP  */
#define TILE134                          135      /* BMP  */
#define TILE135                          136      /* BMP  */
#define TILE136                          137      /* BMP  */
#define TILE137                          138      /* BMP  */
#define TILE138                          139      /* BMP  */
#define TILE139                          140      /* BMP  */
#define TILE140                          141      /* BMP  */
#define TILE141                          142      /* BMP  */
#define TILE142                          143      /* BMP  */
#define TILE143                          144      /* BMP  */
#define TILE144                          145      /* BMP  */
#define TILE145                          146      /* BMP  */
#define TILE146                          147      /* BMP  */
#define TILE147                          148      /* BMP  */
#define TILE148                          149      /* BMP  */
#define TILE149                          150      /* BMP  */
#define TILE150                          151      /* BMP  */
#define TILE151                          152      /* BMP  */
#define TILE152                          153      /* BMP  */
#define TILE153                          154      /* BMP  */
#define TILE154                          155      /* BMP  */
#define TILE155                          156      /* BMP  */
#define TILE156                          157      /* BMP  */
#define TILE157                          158      /* BMP  */
#define TILE158                          159      /* BMP  */
#define TILE159                          160      /* BMP  */
#define TILE160                          161      /* BMP  */
#define TILE161                          162      /* BMP  */
#define TILE162                          163      /* BMP  */
#define TILE163                          164      /* BMP  */
#define TILE164                          165      /* BMP  */
#define TILE165                          166      /* BMP  */
#define TILE166                          167      /* BMP  */
#define TILE167                          168      /* BMP  */
#define TILE168                          169      /* BMP  */
#define TILE169                          170      /* BMP  */
#define TILE170                          171      /* BMP  */
#define TILE171                          172      /* BMP  */
#define TILE172                          173      /* BMP  */
#define TILE173                          174      /* BMP  */
#define TILE174                          175      /* BMP  */
#define TILE175                          176      /* BMP  */
#define TILE176                          177      /* BMP  */
#define TILE177                          178      /* BMP  */
#define TILE178                          179      /* BMP  */
#define TILE179                          180      /* BMP  */
#define TILE180                          181      /* BMP  */
#define TILE181                          182      /* BMP  */
#define TILE182                          183      /* BMP  */
#define TILE183                          184      /* BMP  */
#define TILE184                          185      /* BMP  */
#define TILE185                          186      /* BMP  */
#define TILE186                          187      /* BMP  */
#define TILE187                          188      /* BMP  */
#define TILE188                          189      /* BMP  */
#define TILE189                          190      /* BMP  */
#define TILE190                          191      /* BMP  */
#define TILE191                          192      /* BMP  */
#define TILE192                          193      /* BMP  */
#define TILE193                          194      /* BMP  */
#define TILE194                          195      /* BMP  */
#define TILE195                          196      /* BMP  */
#define TILE196                          197      /* BMP  */
#define TILE197                          198      /* BMP  */
#define TILE198                          199      /* BMP  */
#define TILE199                          200      /* BMP  */
#define TILE200                          201      /* BMP  */
#define TILE201                          202      /* BMP  */
#define TILE202                          203      /* BMP  */
#define TILE203                          204      /* BMP  */
#define TILE204                          205      /* BMP  */
#define TILE205                          206      /* BMP  */
#define TILE206                          207      /* BMP  */
#define TILE207                          208      /* BMP  */
#define TILE208                          209      /* BMP  */
#define TILE209                          210      /* BMP  */
#define TILE210                          211      /* BMP  */
#define TILE211                          212      /* BMP  */
#define TILE212                          213      /* BMP  */
#define TILE213                          214      /* BMP  */
#define TILE214                          215      /* BMP  */
#define TILE215                          216      /* BMP  */
#define TILE216                          217      /* BMP  */
#define TILE217                          218      /* BMP  */
#define TILE218                          219      /* BMP  */
#define TILE219                          220      /* BMP  */
#define TILE220                          221      /* BMP  */
#define TILE221                          222      /* BMP  */
#define TILE222                          223      /* BMP  */
#define TILE223                          224      /* BMP  */
#define TILE224                          225      /* BMP  */
#define TILE225                          226      /* BMP  */
#define TILE226                          227      /* BMP  */
#define TILE227                          228      /* BMP  */
#define TILE228                          229      /* BMP  */
#define TILE229                          230      /* BMP  */
#define TILE230                          231      /* BMP  */
#define TILE231                          232      /* BMP  */
#define TILE232                          233      /* BMP  */
#define TILE233                          234      /* BMP  */
#define TILE234                          235      /* BMP  */
#define TILE235                          236      /* BMP  */
#define TILE236                          237      /* BMP  */
#define TILE237                          238      /* BMP  */
#define TILE238                          239      /* BMP  */
#define TILE239                          240      /* BMP  */
#define TILE240                          241      /* BMP  */
#define TILE241                          242      /* BMP  */
#define TILE242                          243      /* BMP  */
#define TILE243                          244      /* BMP  */
#define TILE244                          245      /* BMP  */
#define TILE245                          246      /* BMP  */
#define TILE246                          247      /* BMP  */
#define TILE247                          248      /* BMP  */
#define TILE248                          249      /* BMP  */
#define TILE249                          250      /* BMP  */
#define TILE250                          251      /* BMP  */
#define TILE251                          252      /* BMP  */
#define TILE252                          253      /* BMP  */
#define TILE253                          254      /* BMP  */
#define TILE254                          255      /* BMP  */
#define TILE255                          256      /* BMP  */

