/* Allegro datafile object indexes, produced by grabber v4.2.2, MinGW32 */
/* Datafile: c:\C\Oddity0.04\dat\gfx.dat */
/* Date: Mon Oct 05 21:29:02 2009 */
/* Do not hand edit! */

#define AANULL                           0        /* BMP  */
#define BEE00                            1        /* BMP  */
#define BEE01                            2        /* BMP  */
#define BONUS00                          3        /* BMP  */
#define BONUS02                          4        /* BMP  */
#define BONUS03                          5        /* BMP  */
#define BONUS_BOUNCE                     6        /* BMP  */
#define BONUS_CASH                       7        /* BMP  */
#define BONUS_FIRE                       8        /* BMP  */
#define BONUS_H00                        9        /* BMP  */
#define BONUS_H01                        10       /* BMP  */
#define BONUS_LAZER                      11       /* BMP  */
#define BONUS_LIFE                       12       /* BMP  */
#define BONUS_MISSILE                    13       /* BMP  */
#define BONUS_OPTION                     14       /* BMP  */
#define BONUS_OUCH                       15       /* BMP  */
#define BONUS_QUESTION                   16       /* BMP  */
#define BONUS_SHIELD                     17       /* BMP  */
#define BONUS_SPEED                      18       /* BMP  */
#define BOULDER00                        19       /* BMP  */
#define BOULDER01                        20       /* BMP  */
#define BOULDER02                        21       /* BMP  */
#define BUBBLE00                         22       /* BMP  */
#define BUBBLE01                         23       /* BMP  */
#define BUBBLE02                         24       /* BMP  */
#define BUBBLE03                         25       /* BMP  */
#define BUILDING00                       26       /* BMP  */
#define BUILDING01                       27       /* BMP  */
#define BUILDING02                       28       /* BMP  */
#define BUILDING03                       29       /* BMP  */
#define BULLET00                         30       /* BMP  */
#define BULLET01                         31       /* BMP  */
#define BULLET02                         32       /* BMP  */
#define BULLET03                         33       /* BMP  */
#define BULLET04                         34       /* BMP  */
#define BULLET05                         35       /* BMP  */
#define BULLET06                         36       /* BMP  */
#define BULLET07                         37       /* BMP  */
#define BULLET08                         38       /* BMP  */
#define BULLET09                         39       /* BMP  */
#define BULLET10                         40       /* BMP  */
#define BULLET11                         41       /* BMP  */
#define BULLET12                         42       /* BMP  */
#define BULLET13                         43       /* BMP  */
#define BULLET14                         44       /* BMP  */
#define BULLET15                         45       /* BMP  */
#define BURST00                          46       /* BMP  */
#define BURST01                          47       /* BMP  */
#define BURST02                          48       /* BMP  */
#define BURST03                          49       /* BMP  */
#define CANON00                          50       /* BMP  */
#define CANON01                          51       /* BMP  */
#define CASH00                           52       /* BMP  */
#define COCKPITBEE00                     53       /* BMP  */
#define COCKPITBEE01                     54       /* BMP  */
#define COCKPITBEE02                     55       /* BMP  */
#define CRAB00                           56       /* BMP  */
#define CRAB01                           57       /* BMP  */
#define CRAB02                           58       /* BMP  */
#define CRAB03                           59       /* BMP  */
#define CREVETTE00                       60       /* BMP  */
#define CREVETTE01                       61       /* BMP  */
#define CREVETTE02                       62       /* BMP  */
#define CREVETTE03                       63       /* BMP  */
#define CREVETTE04                       64       /* BMP  */
#define CREVETTE05                       65       /* BMP  */
#define CROSS                            66       /* BMP  */
#define CURSOR                           67       /* BMP  */
#define DOUBLESHOT00                     68       /* BMP  */
#define DOUBLESHOT01                     69       /* BMP  */
#define DOUBLESHOT02                     70       /* BMP  */
#define DOUBLESHOT03                     71       /* BMP  */
#define DOUBLESHOT04                     72       /* BMP  */
#define DOUBLESHOT05                     73       /* BMP  */
#define EXPLODE00                        74       /* BMP  */
#define EXPLODE01                        75       /* BMP  */
#define EXPLODE02                        76       /* BMP  */
#define EXPLODE03                        77       /* BMP  */
#define EXPLODE04                        78       /* BMP  */
#define FISHSHIP00                       79       /* BMP  */
#define FISHSHIP01                       80       /* BMP  */
#define FISHSHIP02                       81       /* BMP  */
#define FRIENDLY00                       82       /* BMP  */
#define FRIENDLY01                       83       /* BMP  */
#define FRIENDLY02                       84       /* BMP  */
#define FRIENDLY03                       85       /* BMP  */
#define GENERATOR                        86       /* BMP  */
#define HOMING00                         87       /* BMP  */
#define HOMING01                         88       /* BMP  */
#define HOMING02                         89       /* BMP  */
#define HOMING03                         90       /* BMP  */
#define HOMING04                         91       /* BMP  */
#define HOMING05                         92       /* BMP  */
#define HOMING06                         93       /* BMP  */
#define HOMING07                         94       /* BMP  */
#define ICO_BGB_MINUS                    95       /* BMP  */
#define ICO_BGB_PLUS                     96       /* BMP  */
#define ICO_BGG_MINUS                    97       /* BMP  */
#define ICO_BGG_PLUS                     98       /* BMP  */
#define ICO_BGR_MINUS                    99       /* BMP  */
#define ICO_BGR_PLUS                     100      /* BMP  */
#define ICO_CASH                         101      /* BMP  */
#define ICO_DESTROY                      102      /* BMP  */
#define ICO_EMPTY                        103      /* BMP  */
#define ICO_EXIT                         104      /* BMP  */
#define ICO_FADE                         105      /* BMP  */
#define ICO_GAMEOVER                     106      /* BMP  */
#define ICO_MSG1                         107      /* BMP  */
#define ICO_MSG2                         108      /* BMP  */
#define ICO_MSG3                         109      /* BMP  */
#define ICO_MSG4                         110      /* BMP  */
#define ICO_NEXT                         111      /* BMP  */
#define ICO_SPEEDDOWN                    112      /* BMP  */
#define ICO_SPEEDUP                      113      /* BMP  */
#define INVADER00                        114      /* BMP  */
#define INVADER01                        115      /* BMP  */
#define INVADER02                        116      /* BMP  */
#define INVADER03                        117      /* BMP  */
#define JELLY00                          118      /* BMP  */
#define JELLY01                          119      /* BMP  */
#define JELLY02                          120      /* BMP  */
#define JELLY03                          121      /* BMP  */
#define LARVE00                          122      /* BMP  */
#define LARVE01                          123      /* BMP  */
#define LARVE02                          124      /* BMP  */
#define LARVE03                          125      /* BMP  */
#define LARVE99                          126      /* BMP  */
#define LIFE                             127      /* BMP  */
#define MACHOIRE00                       128      /* BMP  */
#define MACHOIRE01                       129      /* BMP  */
#define MACHOIRE02                       130      /* BMP  */
#define MACHOIRE03                       131      /* BMP  */
#define MEDUSE00                         132      /* BMP  */
#define MEDUSE01                         133      /* BMP  */
#define MEDUSE02                         134      /* BMP  */
#define MEDUSE03                         135      /* BMP  */
#define MEDUSE04                         136      /* BMP  */
#define MEDUSE05                         137      /* BMP  */
#define MEDUSE99                         138      /* BMP  */
#define MINE                             139      /* BMP  */
#define MOUCHE00                         140      /* BMP  */
#define MOUCHE01                         141      /* BMP  */
#define MOUCHE02                         142      /* BMP  */
#define MOUCHE03                         143      /* BMP  */
#define MOUCHE99                         144      /* BMP  */
#define MOUSE_CURSOR                     145      /* BMP  */
#define NEST00                           146      /* BMP  */
#define NEST01                           147      /* BMP  */
#define OPTION00                         148      /* BMP  */
#define OPTION01                         149      /* BMP  */
#define OPTION02                         150      /* BMP  */
#define OPTION03                         151      /* BMP  */
#define PARTICULE00                      152      /* BMP  */
#define PARTICULE01                      153      /* BMP  */
#define PARTICULE02                      154      /* BMP  */
#define POW_00                           155      /* BMP  */
#define POW_01                           156      /* BMP  */
#define POW_02                           157      /* BMP  */
#define POW_03                           158      /* BMP  */
#define POW_04                           159      /* BMP  */
#define POW_05                           160      /* BMP  */
#define POW_06                           161      /* BMP  */
#define POW_BOUNCE                       162      /* BMP  */
#define POW_CASH                         163      /* BMP  */
#define POW_HOMING                       164      /* BMP  */
#define POW_LAZER                        165      /* BMP  */
#define POW_LIFE                         166      /* BMP  */
#define PUYO_00                          167      /* BMP  */
#define RIPPLE00                         168      /* BMP  */
#define RIPPLE01                         169      /* BMP  */
#define RIPPLE02                         170      /* BMP  */
#define RIPPLE03                         171      /* BMP  */
#define RIPPLE04                         172      /* BMP  */
#define RIPPLE05                         173      /* BMP  */
#define RIPPLE06                         174      /* BMP  */
#define RIPPLE07                         175      /* BMP  */
#define RIPPLE08                         176      /* BMP  */
#define RIPPLE09                         177      /* BMP  */
#define RIPPLE10                         178      /* BMP  */
#define RIPPLE11                         179      /* BMP  */
#define RIPPLE12                         180      /* BMP  */
#define ROCK00                           181      /* BMP  */
#define ROCK01                           182      /* BMP  */
#define ROCK02                           183      /* BMP  */
#define ROCK03                           184      /* BMP  */
#define ROCK04                           185      /* BMP  */
#define ROCK05                           186      /* BMP  */
#define ROCK06                           187      /* BMP  */
#define ROCKET00                         188      /* BMP  */
#define ROND                             189      /* BMP  */
#define ROND00                           190      /* BMP  */
#define ROND01                           191      /* BMP  */
#define ROTO00                           192      /* BMP  */
#define ROTO01                           193      /* BMP  */
#define ROTO02                           194      /* BMP  */
#define ROTO03                           195      /* BMP  */
#define ROTO04                           196      /* BMP  */
#define ROTO05                           197      /* BMP  */
#define SHIELD00                         198      /* BMP  */
#define SHIELD01                         199      /* BMP  */
#define SHIP00                           200      /* BMP  */
#define SHIP01                           201      /* BMP  */
#define SHIP02                           202      /* BMP  */
#define SHIP03                           203      /* BMP  */
#define SHIP04                           204      /* BMP  */
#define SHIP05                           205      /* BMP  */
#define SHIP06                           206      /* BMP  */
#define SPEED00                          207      /* BMP  */
#define SPEED01                          208      /* BMP  */
#define SPEED02                          209      /* BMP  */
#define SPEED03                          210      /* BMP  */
#define SPEED04                          211      /* BMP  */
#define SPEED05                          212      /* BMP  */
#define SPEED06                          213      /* BMP  */
#define SPEED07                          214      /* BMP  */
#define SPIKE00                          215      /* BMP  */
#define SPIKE01                          216      /* BMP  */
#define SPIKE02                          217      /* BMP  */
#define SPIKE03                          218      /* BMP  */
#define SPRITE03                         219      /* BMP  */
#define SQUARTRON                        220      /* BMP  */
#define STAR00                           221      /* BMP  */
#define STAR01                           222      /* BMP  */
#define STAR02                           223      /* BMP  */
#define STAR03                           224      /* BMP  */
#define STAR04                           225      /* BMP  */
#define STAR05                           226      /* BMP  */
#define STAR06                           227      /* BMP  */
#define STAR07                           228      /* BMP  */
#define STAR08                           229      /* BMP  */
#define TIE00                            230      /* BMP  */
#define TIE01                            231      /* BMP  */
#define TIE02                            232      /* BMP  */
#define TIE03                            233      /* BMP  */
#define TIE04                            234      /* BMP  */
#define TIE05                            235      /* BMP  */
#define TIE06                            236      /* BMP  */
#define TIE07                            237      /* BMP  */

